# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3954b1746bbac0d95ef140d4ef1c8990491588aa3dc84da0b2ba549eff5f5b6a03f9d14fd21e07f2f0cf15ef0b17dbd6b81ce17247906f109368f7f31c166ed7

test:
  secret_key_base: a62784028d80ebfc257c9209e91d1b5fbc691e6c4ce99e2bd8a8839326691f9fb2ea2259b9b241a8687bd34fc011cd88d6eed526e049e45a9eac344d55cd0822

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
